[package]
name = "mi"
version = "0.1.0"
edition = "2018"

[dependencies]
image = "0.23"
threadpool = "1.8.1"
num_cpus = "1.13.0"
lazy_static = "1.4.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"